services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./:/var/www/partir
    user: "${UID}:${GID}"
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/partir
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: