services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - pgsql
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  pgsql:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE} 
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    networks:
      - app-network

volumes:
  pgsql:
    driver: local

networks:
  app-network:
    driver: bridge